models/Media.php
<?php

namespace app\models;

use Yii;
use yii\helpers\FileHelper;
use \yii\behaviors\TimestampBehavior;
use yii\imagine\Image;
/**
 * This is the model class for table "media".
 *
 * @property int $id
 * @property string $title
 * @property string $description
 * @property string $url
 * @property int $type
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 * @property string $created_by
 * @property string $updated_by
 * @property string $album_id
 * @property int $category_id
 * @property string $google_drive_id
 * @property string $google_drive_link
 * @property int $author_id
 */
class Media extends \yii\db\ActiveRecord
{
    
    public $mediaFile;
    /**
     * @var UploadedFile[]
     */
    public $multiMediaFiles;
    
    const TYPE_VIDEO = 1;
    const TYPE_PHOTO = 2;
    
    const STATUS_ACTIVE = 10;
    const STATUS_DELETE = 0;


    const MEDIA_DIR = 'uploads/media/';
    
    private $_employeeSearch;
    public function setEmployeeSearch($employeeSearch) {
        $this->_employeeSearch = $employeeSearch;
    }
    public function getEmployeeSearch() {
        return $this->_employeeSearch;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'media';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['url'], 'string'],
            [['url', 'title', 'description'], 'required'],
            [['category_id'], 'required', 'except' => 'create-by-ajax'],
            
            
            [['type', 'status', 'created_at', 'updated_at', 'album_id', 'category_id'], 'integer'],
            [['author_id'], 'integer', 'message' => '{attribute} không hợp lệ, hãy thêm mới tác giả này'],
            [['title', 'description', 'created_by', 'updated_by','google_drive_link','google_drive_id'], 'string', 'max' => 255],
            [['mediaFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, mp4', 'maxSize' => 1024 * 1024 * 30],
            [['multiMediaFiles'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, mp4', 'maxFiles' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Mô tả',
            'url' => 'Url',
            'type' => 'Type',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'mediaFile' => 'Tải lên',
            'multiMediaFiles' => 'Tải lên', 
            'album_id' => 'Album Id',
            'category_id' => 'Chuyên mục',
            'google_drive_link' => 'Drive link',
            'google_drive_id' => 'Drive id',
            'author_id' => 'Tác giả'
        ];
    }
    
    public function behaviors() {
        return [
            [
                'class' => TimestampBehavior::className()
            ],
        ];
    }
    
    public function upload() {
        if ($this->validate('mediaFile')) {
            $dir = self::MEDIA_DIR.Yii::$app->user->identity->id . '/';
            $type = 'images';
            $this->type = Media::TYPE_PHOTO;
            if($this->mediaFile->extension == 'mp4') {
                $type = 'videos';
                $this->type = Media::TYPE_VIDEO;
            }
            
            $dir = $dir.$type;
            if(!file_exists($dir)) {
                FileHelper::createDirectory($dir);
            }
            
            $path = $dir.'/'.time() . '_' . Yii::$app->security->generateRandomString(5) . '_'. md5($this->mediaFile->baseName) . '.' . $this->mediaFile->extension;
            $this->mediaFile->saveAs($path);
            $this->url = '/'.$path;
            $this->mediaFile = null;
            if($this->type == Media::TYPE_PHOTO) $this->createImageThumb();
            return true;
        } else {
            return false;
        }
    }
    
    public function multiUpload() {
        if ($this->validate('multiMediaFiles')) { 
            $data = [];
            foreach ($this->multiMediaFiles as $file) {
                $dir = self::MEDIA_DIR.Yii::$app->user->identity->id . '/';
                $type = 'images';
                if($file->extension == 'mp4') {
                    $type = 'videos';
                }
                $dir = $dir.$type;
                if(!file_exists($dir)) {
                    FileHelper::createDirectory($dir);
                }

                $path = $dir.'/'.time() . '_' . Yii::$app->security->generateRandomString(5) . '_'. md5($file->baseName) . '.' . $file->extension;
                $file->saveAs($path);
                $data[] = ['url' => '/'.$path, 'type' => $type, 'base_name' => $file->baseName];
                if($type == 'images') $this->createImageThumb('/'.$path);
            }
            return $data;
        } else {
            return false;
        }
    }
    
    public function createImageThumb($source = false) {
        if($source == false) {
            $source = $this->url;
        }
        $thumbName = $this->getThumbName($source);
        $coverThumbName = $this->getThumbName($source, '/cover_');
        
        $origin = Yii::getAlias('@webroot'.$source);
        $thumb = Yii::getAlias('@webroot'.$thumbName);
        $cover = Yii::getAlias('@webroot'.$coverThumbName);
        
        if(file_exists($origin)) {
            Image::thumbnail($origin, 300, 200)
                ->save($thumb, ['quality' => 70]);
            
            Image::thumbnail($origin, 171, 180)
                ->save($cover, ['quality' => 70]);
            return true;
        }
        return false;
    }
    
    public function getThumbName($source = false, $prefix='/thumb_') {
        if($source == false) {
            $source = $this->url;
        }
        $baseName = basename($source);
        $dirName = dirname($source);
        $thumbName = $prefix . $baseName;
        return $dirName.$thumbName;
    }
    
    public function getMediaAlbum() {
        return $this->hasOne(MediaAlbum::className(), ['id' => 'album_id']);
    }
    
    public function getMediaCategory() {
        return $this->hasOne(MediaCategory::className(), ['id' => 'category_id']);
    }
}

controllers/MediaController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Media;
use app\models\MediaSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use app\models\MediaAlbum;
use app\models\MediaAlbumSearch;
use app\components\AdminController;


ini_set('memory_limit', '-1');
ini_set('max_execution_time', 3000); 
/**
 * MediaController implements the CRUD actions for Media model.
 */
class MediaController extends AdminController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Media models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MediaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    

    /**
     * Displays a single Media model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Media model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Media();
        if ($model->load(Yii::$app->request->post())) {
            if($model->author_id == NULL)$model->author_id = Yii::$app->user->identity->id;
            $model->mediaFile = UploadedFile::getInstance($model, 'mediaFile');
            if ($model->upload()) {
                $model->created_by = Yii::$app->user->identity->username;
                $model->updated_by = Yii::$app->user->identity->username;
                if($model->save()) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }
    
    public function actionMultiCreate() {
        $model = new Media();

        if (Yii::$app->request->isPost) {
            $model->multiMediaFiles = UploadedFile::getInstances($model, 'multiMediaFiles');
            $uploadData = $model->multiUpload();
            if ($uploadData && is_array($uploadData) && !empty($uploadData)) {
                foreach($uploadData as $data) {
                    if(isset($data['url']) && $data['url'] != '') {
                        $mediaModel = new Media();
                        $mediaModel->load(Yii::$app->request->post());
                        if($mediaModel->author_id == NULL)$mediaModel->author_id = Yii::$app->user->identity->id;
                        $mediaModel->url = $data['url'];
                        $mediaModel->created_by = Yii::$app->user->identity->username;
                        $mediaModel->updated_by = Yii::$app->user->identity->username;
                        
                        if(isset($data['type'])) {
                            $type = Media::TYPE_VIDEO;
                            if($data['type'] == 'images') {
                                $type = Media::TYPE_PHOTO;
                            }
                            $mediaModel->type = $type;
                        }
                        $mediaModel->save();
                    }
                }
            }
        }

        return $this->render('create', [
            'model' => $model,
            'multiFile' => true,
        ]);
    }

    /**
     * Updates an existing Media model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if(Yii::$app->user->identity->username != 'admin' 
            && $model->created_by != Yii::$app->user->identity->username) {
            throw new \yii\web\ForbiddenHttpException('Bạn không có quyền sửa Media này'); 
        }

        if ($model->load(Yii::$app->request->post())) {
            if($model->author_id == NULL)$model->author_id = Yii::$app->user->identity->id;
            $model->mediaFile = UploadedFile::getInstance($model, 'mediaFile');
            if($model->mediaFile) {
                $model->upload();
            }
            $model->updated_by = Yii::$app->user->identity->username;
            if($model->save()) {
                return $this->redirect(['index']);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Media model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if(Yii::$app->user->identity->username != 'admin' 
            && $model->created_by != Yii::$app->user->identity->username) {
            throw new \yii\web\ForbiddenHttpException('Bạn không có quyền xóa Media này'); 
        }
        $model->status = Media::STATUS_DELETE;
        $model->save();

        return $this->redirect(['index']);
    }
    
    public function actionCreateAlbum() {
        $mediaModel = new Media();
        $albumModel = new MediaAlbum();
        
        if (Yii::$app->request->isPost) {
            $mediaModel->multiMediaFiles = UploadedFile::getInstances($mediaModel, 'multiMediaFiles');
            $uploadData = $mediaModel->multiUpload();
            if ($uploadData && is_array($uploadData) && !empty($uploadData)) {
                $albumModel->load(Yii::$app->request->post());
                if($albumModel->author_id == NULL) $albumModel->author_id = Yii::$app->user->identity->id;
                $albumModel->created_by = Yii::$app->user->identity->username;
                $albumModel->updated_by = Yii::$app->user->identity->username;
                if($albumModel->save()) {
                    foreach($uploadData as $data) {
                        if(isset($data['url']) && $data['url'] != '') {
                            $media = new Media();
                            $media->url = $data['url'];
                            $media->created_by = Yii::$app->user->identity->username;
                            $media->updated_by = Yii::$app->user->identity->username;
                            $media->album_id = $albumModel->id;
                            $media->title = $data['base_name'];
                            $media->description = $albumModel->description;
                            $media->category_id = $albumModel->category_id;
                            $media->author_id = $albumModel->author_id;
                            if(isset($data['type'])) {
                                $type = Media::TYPE_VIDEO;
                                if($data['type'] == 'images') {
                                    $type = Media::TYPE_PHOTO;
                                }
                                $media->type = $type;
                            }
                            $media->save();
                        }
                    }
                    return $this->redirect(['index']);
                }
            }
        }
        
        return $this->render('create-album', [
            'media' => $mediaModel,
            'album' => $albumModel,
        ]);
    }
    
    public function actionAddToAlbum() {
        
    }

    public function actionAlbum() {
        $searchModel = new MediaAlbumSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        return $this->render('album', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionAjaxCreateAlbumUpload() {
        $model = new Media();
        $model->multiMediaFiles = UploadedFile::getInstances($model, 'multiMediaFiles');
        $uploadData = $model->multiUpload();
        
        $return = [];
        if ($uploadData && is_array($uploadData) && !empty($uploadData)) {  
            foreach($uploadData as $data) {
                if(isset($data['url']) && $data['url'] != '') {
                    $media = new Media();
                    $media->scenario = 'create-by-ajax';
                    $media->url = $data['url'];
                    $media->created_by = Yii::$app->user->identity->username;
                    $media->updated_by = Yii::$app->user->identity->username;
                    $media->title = $data['base_name'];
                    $media->description = $data['base_name'];
                    if(isset($data['type'])) {
                        $type = Media::TYPE_VIDEO;
                        if($data['type'] == 'images') {
                            $type = Media::TYPE_PHOTO;
                        }
                        $media->type = $type;
                    }
                    if($media->save()){
                        $return[] = $media->id;
                    }
                }
            }         
        }
        return json_encode($return);
    }



views/media/_form-album-ajax.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Media */
/* @var $form yii\widgets\ActiveForm */
use kartik\file\FileInput;
use kartik\select2\Select2;
use yii\web\JsExpression;
use yii\web\View;
use yii\helpers\Url;
?>


<?php 
$formatJs = <<< 'JS'
function IsNumeric(input){
    var RE = /^-{0,1}\d*\.{0,1}\d+$/;
    return (RE.test(input));
};
var formatEmployee = function(employee){
        if(employee.id != 'undefined' && IsNumeric(employee.id)) {
            var imx = 'uploads/images/users/no-user-image.png';
            if(employee.image != 'undefined' && employee.image != null) {
                imx = employee.image;
            }
            var ma = '<div class="row">' + 
                    '<div class="col-md-12">' +
                        '<img data-holder-rendered="true" style="width: 64px; height: 64px; data-src="holder.js/64x64" src="/' + imx + '" class="img-rounded" />' + 
                        '<b style="margin-left:5px">' + employee.text + '</b>' + 
                    '</div>' + 
                '</div>';
            return '<div style="overflow:hidden;">' + ma + '</div>';
        }
    };
    
var formatSelectionEmployee = function(employee) {
    return employee.full_name || employee.text;
};


var eventSelectEmployee = function(item) {
    if(item.params.data.selected) {
        console.log(item.params.data);
    }
};

var eventFileBatchSelected = function(event, files) {
    $("#hungls-uploads").fileinput("upload");;
};

var eventFileBatchUploadSuccess = function(event, data) {
    if(Object.keys(data.response).length > 0) {
        var stringId = '';
        for(var prop in data.response) {
            if(stringId == '') {
                stringId = data.response[prop];
            } else {
                stringId = stringId + ',' + data.response[prop];
            }
        }
        
        if($('#mediaalbum-mediaidstring').val() != '') {
            stringId = stringId + ',' + $('#mediaalbum-mediaidstring').val();
        }
        $('#mediaalbum-mediaidstring').val(stringId);
    }
};

JS;

$this->registerJs($formatJs, View::POS_HEAD);
$this->registerJsFile('/js/media-item.js', ['depends' => [\yii\web\JqueryAsset::className()], 'position' => View::POS_END]);?>

<div class="media-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="col-md-6"><?= $form->field($album, 'name')->textInput(['maxlength' => true]) ?></div>
        <div class="col-md-6"><?= $form->field($album, 'description')->textInput(['maxlength' => true]) ?></div>
        <div class="col-md-6"><?= $form->field($album, 'mediaIdString')->hiddenInput()->label(false) ?></div>
    </div>

    <div class="row">
        <div class="col-md-6"><?= $form->field($album, 'category_id')->dropDownList([''=>'---- Chọn chuyên mục ----'] + \app\models\MediaCategory::getListCategory()) ?></div>
        <div class="col-md-6">
            <?php $url = Yii::$app->urlManager->createUrl(['employee/ajax-get-employee-list']);?>
            <?php echo $form->field($album, 'author_id')->widget(Select2::classname(), [
                'initValueText' => app\models\Employee::getAliasAuthorById($album->author_id),
                'options' => ['placeholder' => 'Chọn tác giả', 'id' => 'media-select-author-id'],
                'pluginOptions' => [
                    'allowClear' => true,
                    'minimumInputLength' => 2,
                    'language' => [
                        'errorLoading' => new JsExpression("function () { return 'Đang tìm dữ liệu...'; }"),
                    ],
                    'ajax' => [
                        'url' => $url,
                        'dataType' => 'json',
                        'data' => new JsExpression('function(params) { return {q:params.term}; }'),
                        'delay' => 250,
                    ],
                    'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                    'templateResult' => new JsExpression('formatEmployee'),
                    'templateSelection' => new JsExpression('formatSelectionEmployee'),
                    'tags' => true,
                    //'width' => '300px',
                ],
                'pluginEvents' => [
                    'select2:select' => new JsExpression('eventSelectEmployee'),
                ],
                'addon' => [
                    'append' => [
                        'content' => Html::button('<span class="glyphicon glyphicon-plus"></span>', [
                            'class' => 'btn btn-primary', 
                            'style' => 'height: 99%;',
                            'id' => 'btn-add-author',
                            'title' => 'Thêm tác giả', 
                            'data-toggle' => 'tooltip'
                        ]),
                        'asButton' => true
                    ]
                ]

            ]);?>
        </div>
    </div>

    <?php 
        $pluginOptions = [
            'maxFileSize' => 30000, 
            'uploadUrl' => Url::to(['/media/ajax-create-album-upload']),
            'uploadAsync' => false,
            'showUpload' => false,
            'showRemove' => false,
        ];
        
        echo $form->field($media, 'multiMediaFiles[]')->widget(FileInput::classname(),[
            'options' => ['multiple' => true, 'accept' => 'image/*', 'id' => 'hungls-uploads'],
            'pluginOptions' => $pluginOptions,
            'pluginEvents' => [
                'filebatchselected' => new JsExpression('eventFileBatchSelected'),
                'filebatchuploadsuccess' => new JsExpression('eventFileBatchUploadSuccess'),
            ]
        ]); 
    ?>
    
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/media/_form-album.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Media */
/* @var $form yii\widgets\ActiveForm */
use kartik\file\FileInput;
use kartik\select2\Select2;
use yii\web\JsExpression;
use yii\web\View;
?>


<?php 
$formatJs = <<< 'JS'
function IsNumeric(input){
    var RE = /^-{0,1}\d*\.{0,1}\d+$/;
    return (RE.test(input));
};
var formatEmployee = function(employee){
        if(employee.id != 'undefined' && IsNumeric(employee.id)) {
            var imx = 'uploads/images/users/no-user-image.png';
            if(employee.image != 'undefined' && employee.image != null) {
                imx = employee.image;
            }
            var ma = '<div class="row">' + 
                    '<div class="col-md-12">' +
                        '<img data-holder-rendered="true" style="width: 64px; height: 64px; data-src="holder.js/64x64" src="/' + imx + '" class="img-rounded" />' + 
                        '<b style="margin-left:5px">' + employee.text + '</b>' + 
                    '</div>' + 
                '</div>';
            return '<div style="overflow:hidden;">' + ma + '</div>';
        }
    };
    
var formatSelectionEmployee = function(employee) {
    return employee.full_name || employee.text;
};


var eventSelectEmployee = function(item) {
    if(item.params.data.selected) {
        //console.log(item.params.data);
    }
};
JS;

$this->registerJs($formatJs, View::POS_HEAD);
$this->registerJsFile('/js/media-item.js', ['depends' => [\yii\web\JqueryAsset::className()], 'position' => View::POS_END]); ?>

<div class="media-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="col-md-6"><?= $form->field($album, 'name')->textInput(['maxlength' => true]) ?></div>
        <div class="col-md-6"><?= $form->field($album, 'description')->textInput(['maxlength' => true]) ?></div>
    </div>

    <div class="row">
        <div class="col-md-6"><?= $form->field($album, 'category_id')->dropDownList([''=>'---- Chọn chuyên mục ----'] + \app\models\MediaCategory::getListCategory()) ?></div>
        <div class="col-md-6">
            <?php $url = Yii::$app->urlManager->createUrl(['employee/ajax-get-employee-list']);?>
            <?php echo $form->field($album, 'author_id')->widget(Select2::classname(), [
                'initValueText' => app\models\Employee::getAliasAuthorById($album->author_id),
                'options' => ['placeholder' => 'Chọn tác giả', 'id' => 'media-select-author-id'],
                'pluginOptions' => [
                    'allowClear' => true,
                    'minimumInputLength' => 2,
                    'language' => [
                        'errorLoading' => new JsExpression("function () { return 'Đang tìm dữ liệu...'; }"),
                    ],
                    'ajax' => [
                        'url' => $url,
                        'dataType' => 'json',
                        'data' => new JsExpression('function(params) { return {q:params.term}; }'),
                        'delay' => 250,
                    ],
                    'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                    'templateResult' => new JsExpression('formatEmployee'),
                    'templateSelection' => new JsExpression('formatSelectionEmployee'),
                    'tags' => true,
                    //'width' => '300px',
                ],
                'pluginEvents' => [
                    'select2:select' => new JsExpression('eventSelectEmployee'),
                ],
                'addon' => [
                    'append' => [
                        'content' => Html::button('<span class="glyphicon glyphicon-plus"></span>', [
                            'class' => 'btn btn-primary', 
                            'style' => 'height: 99%;',
                            'id' => 'btn-add-author',
                            'title' => 'Thêm tác giả', 
                            'data-toggle' => 'tooltip'
                        ]),
                        'asButton' => true
                    ]
                ]

            ]);?>
        </div>
    </div>

    <?php 
        $pluginOptions = ['maxFileSize' => 30000];
        echo $form->field($media, 'multiMediaFiles[]')->widget(FileInput::classname(), [
            'options' => ['multiple' => true,'accept' => 'image/*'],
            'pluginOptions' => $pluginOptions
        ]); 
    ?>
    
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/media/_form-multi.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Media */
/* @var $form yii\widgets\ActiveForm */
use kartik\file\FileInput;
?>

<div class="media-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

    <?php 
        $pluginOptions = ['maxFileSize' => 30000];
        echo $form->field($model, 'multiMediaFiles[]')->widget(FileInput::classname(), [
            'options' => ['multiple' => true],
            'pluginOptions' => $pluginOptions
        ]); 
    ?>
    
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/media/album.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\MediaAlbumSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Albums';
$this->params['breadcrumbs'][] = ['label' => 'Media', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
    .row .summary {
        margin-left: 15px;
    }
    .row .pagination {
        margin-left: 15px;
    }
    .row .empty {
        margin-left: 15px;
    }
</style>
<div class="media-album-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <p><?php echo $this->render('_search-album', ['model' => $searchModel]); ?></p>

    <p>
        <?= Html::a('Tạo Media Album', ['create-album-ajax'], ['class' => 'btn btn-success']) ?>
    </p>

    <div class="row">
        <?php 
        echo ListView::widget([
        'dataProvider' => $dataProvider,
            'itemView' => '_album_item',
        ]);
        ?>
    </div>
</div>

views/media/create-album-ajax.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Media */

$this->title = 'Tạo Media Album';
$this->params['breadcrumbs'][] = ['label' => 'Media', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'Albums', 'url' => ['album']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="media-create">

    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form-album-ajax', [
        'media' => $media,
        'album' => $album
    ]) ?>
</div>

views/media/create-album.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Media */

$this->title = 'Tạo Media Album';
$this->params['breadcrumbs'][] = ['label' => 'Media', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'Albums', 'url' => ['album']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="media-create">

    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form-album', [
        'media' => $media,
        'album' => $album
    ]) ?>
</div>

views/media/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Media */

$this->title = 'Create Media';
$this->params['breadcrumbs'][] = ['label' => 'Media', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="media-create">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php if(isset($multiFile) && $multiFile):?>
    <?= $this->render('_form-multi', [
        'model' => $model,
    ]) ?>
    <?php else: ?>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
    <?php endif;?>
</div>

views/media/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Media */

$this->title = 'Update Media: {nameAttribute}';
$this->params['breadcrumbs'][] = ['label' => 'Media', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="media-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>